name: Aranha TiePadel Automatica

on:
  schedule:
    # 0 = Minuto
    # 2 = Hora (Atenção: O GitHub usa o fuso horário UTC)
    # * = Todos os dias do mês
    # * = Todos os meses
    # 1,5 = Segunda (1) e Sexta (5)
    - cron: '0 2 * * 1,5'

  # Permite correr manualmente para testes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar o código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Instalar Puppeteer e Dependências
        run: npm ci

      - name: 🕷️ Executar a Aranha
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_SN_LIGA }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_SN_LIGA }}
        run: node scraperLiga.js